apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsim
  labels:
    app: microsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsim
  template:
    metadata:
      labels:
        app: microsim
    spec:
      containers:
        - name: microsim
          image: yurishkuro/microsim:latest
          ports:
            - containerPort: 8080
          env:
            - name: MICROSIM_SERVICE_NAME
              value: "frontend"
            - name: MICROSIM_SERVICE_GRAPH
              value: '{"frontend":["service-a"],"service-a":["service-b"],"service-b":[]}'
            - name: MICROSIM_SERVER_PORT
              value: "8080"
            - name: OTEL_TRACES_SAMPLER
              value: "always_off"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0"