apiVersion: v1
kind: Service
metadata:
  name: microsim
  labels:
    app: microsim
spec:
  selector:
    app: microsim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # type: ClusterIP
  type: LoadBalancer
