# values.yaml

prometheus:
  prometheusSpec:
    retention: "7d"
    resources:
      requests:
        # memory: "512Mi"
        memory: "256Mi"
        # cpu: "200m"
        cpu: "100m"
      limits:
        # memory: "1Gi"
        memory: "512Mi"
        # cpu: "500m"
        cpu: "200m"
    service:
      type: LoadBalancer

grafana:
  enabled: true
  adminPassword: "mySecurePassword"
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100/
  service:
    type: LoadBalancer

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "300m"
