# kube-prometheus-stack Helm values
# This includes Prometheus, Grafana, and Alertmanager

# Grafana configuration
grafana:
  enabled: true
  
  # Expose Grafana via LoadBalancer
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  
  # Enable persistence for dashboards
  persistence:
    enabled: true
    size: 10Gi
  
  # Configure default data sources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://kube-prom-stack-kube-prome-prometheus:9090
          access: proxy
          isDefault: true

# Prometheus configuration
prometheus:
  enabled: true
  
  # Configure retention and storage
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
  
  # Configure service discovery
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

# Alertmanager configuration
alertmanager:
  enabled: true
  
  # Configure persistence
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

# Node Exporter for node metrics
nodeExporter:
  enabled: true

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# Prometheus Operator
prometheusOperator:
  enabled: true

# Default rules and dashboards
defaultRules:
  enabled: true
  create: true

# Grafana dashboards
grafanaDashboards:
  default:
    k8s-cluster:
      gnetId: 315
      revision: 3
      datasource: Prometheus
    k8s-node:
      gnetId: 1860
      revision: 22
      datasource: Prometheus
    k8s-pod:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    k8s-service:
      gnetId: 6418
      revision: 1
      datasource: Prometheus

# RBAC configuration
rbac:
  create: true

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534
